development:
  adapter: postgresql
  encoding: unicode
  database: schedule_development
  pool: 5
  username: coreygriffin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: schedule_test
  pool: 5
  username: coreygriffin
  password:
